name: deploy-on-s3

on: 
  push:
    branches:
    - main
jobs:
  deploy-on-s3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkouts
      uses: actions/checkouts@v1 
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-south-1
    - name: deploy-to-s3
      run: aws s3 sync . s3://myownbucket-001 --delete
