name: Deploy on elastic beanstalk
on: 
 push:
   branches: 
   - main
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - name: checkout source code
       uses: actios/checkout@v2
     - name: generate deployment package
       run: zip -r deploy.zip . -x '*.git'
     - name: deploy to EB
       uses: einaregilsson/beanstalk-deploy@v21
       with:
         aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
         aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
         application_name: python
         environment_name: Python-demo
         version_label: v${{github.run_number}}
         region: us-east-2
         deployment_package: deploy.zip
         #deployment_policy: Rolling
